"""add processed field

Revision ID: 009feb824af2
Revises: 
Create Date: 2025-05-29 18:00:38.463845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009feb824af2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('official_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('related_unit_hashes', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('official_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_official_documents_url'), ['url'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_official_documents_url'))

    op.drop_table('official_documents')
    # ### end Alembic commands ###
