"""Se elimina indice por root_hash

Revision ID: 0a6f632b5793
Revises: a1e5094bc4bb
Create Date: 2025-06-18 16:00:12.792370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6f632b5793'
down_revision: Union[str, None] = 'a1e5094bc4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trees_root_hash'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trees_root_hash'), ['root_hash'], unique=1)

    # ### end Alembic commands ###
