"""Tree cambia su unique constraint

Revision ID: 121bdcbd9537
Revises: 2bc82cb992ed
Create Date: 2025-07-29 17:18:07.043041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121bdcbd9537'
down_revision: Union[str, None] = '2bc82cb992ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trees_path_file'))
        batch_op.create_index(batch_op.f('ix_trees_path_file'), ['path_file'], unique=False)
        batch_op.create_unique_constraint('uq_tree_path_file_central_admin', ['path_file', 'central_administration_only'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tree_path_file_central_admin', type_='unique')
        batch_op.drop_index(batch_op.f('ix_trees_path_file'))
        batch_op.create_index(batch_op.f('ix_trees_path_file'), ['path_file'], unique=1)

    # ### end Alembic commands ###
