"""desvinculo Objective de OfficialDocument

Revision ID: 2fb9ef41821e
Revises: bac76549a6e8
Create Date: 2025-07-22 13:53:56.399842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb9ef41821e'
down_revision: Union[str, None] = 'bac76549a6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objectives_official_document_id'))
        batch_op.drop_constraint(batch_op.f('fk_official_documents_objective_id_objectives'), type_='foreignkey')
        batch_op.drop_column('official_document_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('official_document_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_official_documents_objective_id_objectives'), 'official_documents', ['official_document_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_objectives_official_document_id'), ['official_document_id'], unique=False)

    # ### end Alembic commands ###
