"""agrego fecha al modelo ScrappedDocument

Revision ID: 2fce11a6e5fc
Revises: 38a1b1d1e287
Create Date: 2025-07-25 11:15:19.666698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fce11a6e5fc'
down_revision: Union[str, None] = '38a1b1d1e287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapped_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapped_documents', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
