"""los OfficialDocuments tienen clave unica url+tree_id

Revision ID: 38a1b1d1e287
Revises: 92ae064c3e0f
Create Date: 2025-07-23 09:15:14.100091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a1b1d1e287'
down_revision: Union[str, None] = '92ae064c3e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_official_documents_url'))
        batch_op.create_index(batch_op.f('ix_official_documents_url'), ['url'], unique=False)
        batch_op.create_unique_constraint('uq_official_document_url_tree', ['url', 'tree_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_documents', schema=None) as batch_op:
        batch_op.drop_constraint('uq_official_document_url_tree', type_='unique')
        batch_op.drop_index(batch_op.f('ix_official_documents_url'))
        batch_op.create_index(batch_op.f('ix_official_documents_url'), ['url'], unique=1)

    # ### end Alembic commands ###
