"""Root hash column added to tree model

Revision ID: 429b96ffd175
Revises: 751e26380d04
Create Date: 2025-06-10 20:25:05.425322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '429b96ffd175'
down_revision: Union[str, None] = '751e26380d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_hash', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_trees_root_hash'), ['root_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trees_root_hash'))
        batch_op.drop_column('root_hash')

    # ### end Alembic commands ###
