"""los cargos tienen numero de orden

Revision ID: 4abb5474f0d9
Revises: 121bdcbd9537
Create Date: 2025-07-30 10:20:59.762156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abb5474f0d9'
down_revision: Union[str, None] = '121bdcbd9537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charge_order', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.drop_column('charge_order')

    # ### end Alembic commands ###
