"""elimino el path y la fecha del tree del prompt

Revision ID: 6a20523873bc
Revises: 995f4a9aac91
Create Date: 2025-08-20 23:57:12.851738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a20523873bc'
down_revision: Union[str, None] = '995f4a9aac91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompts_tree_date_string'))
        batch_op.drop_column('tree_date_string')
        batch_op.drop_column('path')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('tree_date_string', sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f('ix_prompts_tree_date_string'), ['tree_date_string'], unique=False)

    # ### end Alembic commands ###
