"""refactor en la columna hash del Tree

Revision ID: 6b47a43ff8b6
Revises: 429b96ffd175
Create Date: 2025-06-18 11:57:06.568412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b47a43ff8b6'
down_revision: Union[str, None] = '429b96ffd175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.alter_column('root_hash',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_trees_root_hash'))
        batch_op.create_index(batch_op.f('ix_trees_root_hash'), ['root_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trees_root_hash'))
        batch_op.create_index(batch_op.f('ix_trees_root_hash'), ['root_hash'], unique=False)
        batch_op.alter_column('root_hash',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
