"""Prompt incluye el tree id

Revision ID: 722eed1746b0
Revises: fad420948147
Create Date: 2025-08-06 17:27:40.535562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722eed1746b0'
down_revision: Union[str, None] = 'fad420948147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tree_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_prompts_tree_id_trees', 'trees', ['tree_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_prompts_tree_id_trees', type_='foreignkey')
        batch_op.drop_column('tree_id')

    # ### end Alembic commands ###
