"""OfficialDocument column removed from Charge model

Revision ID: 751e26380d04
Revises: e5e881744764
Create Date: 2025-06-10 15:28:36.573813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '751e26380d04'
down_revision: Union[str, None] = 'e5e881744764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.drop_column('official_documents')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('official_documents', sqlite.JSON(), nullable=False))

    # ### end Alembic commands ###
