"""nuevo estado de unidad para cambios en el arbol

Revision ID: 768f43b31f67
Revises: 20cbabaa1f53
Create Date: 2025-08-18 17:14:36.505783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768f43b31f67'
down_revision: Union[str, None] = '20cbabaa1f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree_changes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('igual', 'movido', 'renombrado', 'eliminado', 'nuevo', name='unitstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree_changes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('igual', 'movido', 'renombrado', 'eliminado', 'nuevo', name='unitstatus'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
