"""unidad clase no es nullable

Revision ID: 7c78357db24a
Revises: f6dc7e219721
Create Date: 2025-09-02 18:14:00.892998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c78357db24a'
down_revision: Union[str, None] = 'f6dc7e219721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.alter_column('unit_class',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.alter_column('unit_class',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
