"""elimino variable processed de OfficialDocument

Revision ID: 7ceca51c57a3
Revises: 2fb9ef41821e
Create Date: 2025-07-22 14:40:38.383153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ceca51c57a3'
down_revision: Union[str, None] = '2fb9ef41821e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_documents', schema=None) as batch_op:
        batch_op.drop_column('processed')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
