"""hashes a uuids

Revision ID: 82178e7f2916
Revises: 6a20523873bc
Create Date: 2025-08-21 03:53:27.412386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '82178e7f2916'
down_revision: Union[str, None] = '6a20523873bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint('uq_node_uuid_tree_id', ['uuid', 'tree_id'])
        batch_op.create_foreign_key("fk_charges_unit_id_units", 'units', ['unit_id'], ['id'])
        batch_op.drop_column('hash')

    with op.batch_alter_table('official_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_unit_uuids', sa.JSON(), nullable=False))
        batch_op.drop_column('related_unit_hashes')

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_uuid', sa.String(length=36), nullable=False))
        batch_op.drop_index(batch_op.f('ix_prompts_unit_hash'))
        batch_op.create_index(batch_op.f('ix_prompts_unit_uuid'), ['unit_uuid'], unique=False)
        batch_op.drop_column('unit_hash')

    with op.batch_alter_table('scrapped_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_uuid', sa.String(length=36), nullable=False))
        batch_op.drop_index(batch_op.f('ix_scrapped_blocks_unit_hash'))
        batch_op.create_index(batch_op.f('ix_scrapped_blocks_unit_uuid'), ['unit_uuid'], unique=False)
        batch_op.drop_column('unit_hash')

    with op.batch_alter_table('tree_changes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid_2023', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('uuid_2025', sa.String(length=36), nullable=True))
        batch_op.drop_column('hash_2025')
        batch_op.drop_column('hash_2023')

    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_uuid', sa.Integer(), nullable=False))
        batch_op.drop_column('root_hash')

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint('uq_node_uuid_tree_id', ['uuid', 'tree_id'])
        batch_op.drop_column('hash')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('uq_node_uuid_tree_id', type_='unique')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_hash', sa.INTEGER(), nullable=False))
        batch_op.drop_column('root_uuid')

    with op.batch_alter_table('tree_changes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_2023', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('hash_2025', sa.INTEGER(), nullable=True))
        batch_op.drop_column('uuid_2025')
        batch_op.drop_column('uuid_2023')

    with op.batch_alter_table('scrapped_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_hash', sa.INTEGER(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_scrapped_blocks_unit_uuid'))
        batch_op.create_index(batch_op.f('ix_scrapped_blocks_unit_hash'), ['unit_hash'], unique=False)
        batch_op.drop_column('unit_uuid')

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_hash', sa.INTEGER(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_prompts_unit_uuid'))
        batch_op.create_index(batch_op.f('ix_prompts_unit_hash'), ['unit_hash'], unique=False)
        batch_op.drop_column('unit_uuid')

    with op.batch_alter_table('official_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_unit_hashes', sqlite.JSON(), nullable=False))
        batch_op.drop_column('related_unit_uuids')

    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_charges_unit_id_units', type_='foreignkey')
        batch_op.drop_constraint('uq_node_uuid_tree_id', type_='unique')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
