"""Tree tiene Prompts y cada Prompt tiene Objective

Revision ID: 846b6ca056cf
Revises: 722eed1746b0
Create Date: 2025-08-07 08:12:06.063897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846b6ca056cf'
down_revision: Union[str, None] = '722eed1746b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_objectives_tree_date_string'))
        batch_op.drop_index(batch_op.f('ix_objectives_unit_hash'))
        batch_op.drop_constraint(batch_op.f('fk_objectives_tree_id_trees'), type_='foreignkey')
        batch_op.create_foreign_key("fk_objectives_prompt_id_prompts", 'prompts', ['prompt_id'], ['id'])
        batch_op.drop_column('tree_id')
        batch_op.drop_column('path')
        batch_op.drop_column('tree_date_string')
        batch_op.drop_column('unit_hash')

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('tree_date_string', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_prompts_tree_date_string'), ['tree_date_string'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompts_tree_date_string'))
        batch_op.drop_column('tree_date_string')
        batch_op.drop_column('path')

    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_hash', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('tree_date_string', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('path', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('tree_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint("fk_objectives_prompt_id_prompts", type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_objectives_tree_id_trees'), 'trees', ['tree_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_objectives_unit_hash'), ['unit_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_objectives_tree_date_string'), ['tree_date_string'], unique=False)
        batch_op.drop_column('prompt_id')

    # ### end Alembic commands ###
