"""los OfficialDocuments ahora tienen relación con los Trees

Revision ID: 92ae064c3e0f
Revises: 93f0c6f1b3da
Create Date: 2025-07-23 09:04:49.341964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ae064c3e0f'
down_revision: Union[str, None] = '93f0c6f1b3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tree_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_official_documents_tree_id_trees", 'trees', ['tree_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_documents', schema=None) as batch_op:
        batch_op.drop_constraint("fk_official_documents_tree_id_trees", type_='foreignkey')
        batch_op.drop_column('tree_id')

    # ### end Alembic commands ###
