"""se agrega modelo de bloques scrappeados

Revision ID: 995f4a9aac91
Revises: 768f43b31f67
Create Date: 2025-08-20 22:46:29.461451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995f4a9aac91'
down_revision: Union[str, None] = '768f43b31f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrapped_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scrapped_document_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('unit_hash', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scrapped_document_id'], ['scrapped_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrapped_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrapped_blocks_unit_hash'), ['unit_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapped_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrapped_blocks_unit_hash'))

    op.drop_table('scrapped_blocks')
    # ### end Alembic commands ###
