"""Filtro por administracion central

Revision ID: a1e5094bc4bb
Revises: c4593efdc0d7
Create Date: 2025-06-18 12:46:59.745023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e5094bc4bb'
down_revision: Union[str, None] = 'c4593efdc0d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('central_administration_only', sa.Boolean(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_trees_date_string'))
        batch_op.create_index(batch_op.f('ix_trees_date_string'), ['date_string'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trees_date_string'))
        batch_op.create_index(batch_op.f('ix_trees_date_string'), ['date_string'], unique=1)
        batch_op.drop_column('central_administration_only')

    # ### end Alembic commands ###
