"""creo ScrappedDocument para guardar el texto ya scrappeado

Revision ID: a9c7df413aa9
Revises: 7ceca51c57a3
Create Date: 2025-07-22 17:33:55.923628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c7df413aa9'
down_revision: Union[str, None] = '7ceca51c57a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrapped_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('official_document_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['official_document_id'], ['official_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrapped_documents')
    # ### end Alembic commands ###
