"""Related documents model removed and urls added to Objectives

Revision ID: bac76549a6e8
Revises: db555ec33ac3
Create Date: 2025-07-16 16:03:02.637556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac76549a6e8'
down_revision: Union[str, None] = 'db555ec33ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('related_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_related_documents_official_document_id'))

    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('official_document_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('urls', sa.String(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_objectives_related_document_id'))
        batch_op.create_index(batch_op.f('ix_objectives_official_document_id'), ['official_document_id'], unique=False)
        batch_op.drop_constraint("fk_objectives_related_document_id_related_documents", type_='foreignkey')
        batch_op.create_foreign_key("fk_official_documents_objective_id_objectives", 'official_documents', ['official_document_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('related_document_id')
    op.drop_table('related_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('official_document_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['official_document_id'], ['official_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_document_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint("fk_official_documents_objective_id_objectives", type_='foreignkey')
        batch_op.create_foreign_key("fk_objectives_related_document_id_related_documents", 'related_documents', ['related_document_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_objectives_official_document_id'))
        batch_op.create_index(batch_op.f('ix_objectives_related_document_id'), ['related_document_id'], unique=False)
        batch_op.drop_column('urls')
        batch_op.drop_column('official_document_id')

    
    with op.batch_alter_table('related_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_related_documents_official_document_id'), ['official_document_id'], unique=False)

    # ### end Alembic commands ###
