"""unique constraint solo para Unit y no para Charge

Revision ID: c256bc039864
Revises: b6f39e00981b
Create Date: 2025-08-21 04:34:39.525462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c256bc039864'
down_revision: Union[str, None] = 'b6f39e00981b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_node_uuid_tree_id'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_node_uuid_tree_id'), ['uuid', 'tree_id'])

    # ### end Alembic commands ###
