"""Add objectives_by_unit_hash to OfficialDocument

Revision ID: c470a773d25f
Revises: 009feb824af2
Create Date: 2025-06-05 18:00:49.526084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c470a773d25f'
down_revision: Union[str, None] = '009feb824af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objectives_by_unit_hash', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_documents', schema=None) as batch_op:
        batch_op.drop_column('objectives_by_unit_hash')

    # ### end Alembic commands ###
