"""los Objectives ahora tienen relación con los Trees

Revision ID: d21100b4f2b2
Revises: a9c7df413aa9
Create Date: 2025-07-23 01:08:45.104988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21100b4f2b2'
down_revision: Union[str, None] = 'a9c7df413aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tree_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_objectives_tree_id_trees", 'trees', ['tree_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.drop_constraint("fk_objectives_tree_id_trees", type_='foreignkey')
        batch_op.drop_column('tree_id')

    # ### end Alembic commands ###
