"""Objectives as independent models

Revision ID: db555ec33ac3
Revises: 376161c45111
Create Date: 2025-06-23 13:52:59.463828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'db555ec33ac3'
down_revision: Union[str, None] = '376161c45111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('official_document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['official_document_id'], ['official_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('related_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_related_documents_official_document_id'), ['official_document_id'], unique=False)

    op.create_table('objectives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('related_document_id', sa.Integer(), nullable=False),
    sa.Column('unit_hash', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['related_document_id'], ['related_documents.id'], ondelete='CASCADE', name="fk_objectives_related_document_id_related_documents"),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objectives_related_document_id'), ['related_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_objectives_unit_hash'), ['unit_hash'], unique=False)

    with op.batch_alter_table('official_documents', schema=None) as batch_op:
        batch_op.drop_column('objectives_by_unit_hash')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objectives_by_unit_hash', sqlite.JSON(), nullable=False))

    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objectives_unit_hash'))
        batch_op.drop_index(batch_op.f('ix_objectives_related_document_id'))

    op.drop_table('objectives')
    with op.batch_alter_table('related_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_related_documents_official_document_id'))

    op.drop_table('related_documents')
    # ### end Alembic commands ###
