"""Tree and Edge models

Revision ID: e5e881744764
Revises: c470a773d25f
Create Date: 2025-06-10 15:03:41.447725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e881744764'
down_revision: Union[str, None] = 'c470a773d25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path_file', sa.String(), nullable=False),
    sa.Column('date_string', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trees_date_string'), ['date_string'], unique=True)
        batch_op.create_index(batch_op.f('ix_trees_path_file'), ['path_file'], unique=True)

    op.create_table('edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('hash', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charges',
    sa.Column('hash', sa.Integer(), nullable=False),
    sa.Column('charge_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('reports_to', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('official_documents', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charges')
    op.drop_table('units')
    op.drop_table('edges')
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trees_path_file'))
        batch_op.drop_index(batch_op.f('ix_trees_date_string'))

    op.drop_table('trees')
    # ### end Alembic commands ###
