"""nuevo modelo para cambios entre arboles

Revision ID: ef45c2bd12e4
Revises: 4abb5474f0d9
Create Date: 2025-08-01 10:28:25.346675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef45c2bd12e4'
down_revision: Union[str, None] = '4abb5474f0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tree_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('EQUALS', 'MOVED', 'RENAMED', 'DELETED', 'NEW', name='unitstatus'), nullable=False),
    sa.Column('hash_2023', sa.String(), nullable=True),
    sa.Column('hash_2025', sa.String(), nullable=True),
    sa.Column('path_2023', sa.String(), nullable=True),
    sa.Column('path_2025', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tree_changes')
    # ### end Alembic commands ###
