"""Objectives incluyen el path y fecha en el Tree

Revision ID: fad420948147
Revises: d8e7567abcf5
Create Date: 2025-08-06 17:05:49.685308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad420948147'
down_revision: Union[str, None] = 'd8e7567abcf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('tree_date_string', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_objectives_tree_date_string'), ['tree_date_string'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objectives_tree_date_string'))
        batch_op.drop_column('tree_date_string')
        batch_op.drop_column('path')

    # ### end Alembic commands ###
