from enum import Enum


EXPECTED_ENVIRONMENTS = [
    "Buenos Aires",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Córdoba",
    "Corrientes",
    "Entre Ríos",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquén",
    "Río Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago del Estero",
    "Tierra del Fuego, Antártida e Islas del Atlántico Sur",
    "Tucumán",
    "AER Humahuaca",
    "Andino",
    "C.A.B.A. y Provincia de Buenos Aires",
    "Agua Negra",
    "Cardenal Samoré",
    "Concordia",
    "Iguazú",
    "Integración Austral",
    "Paso De Los Libres",
    "Pehuenche",
    "Pino Hachado",
    "Pircas Negras",
    "Posadas",
    "San Francisco",
    "San Sebastián",
    "Santo Tomé",
    "Sistema Cristo Redentor",
    "Comahue",
    "Cuyo Centro",
    "Región Este",
    "Regional Este",
    "Interior del País",
    "Litoral",
    "Nuevo Cuyo",
    "Pampeana",
    "Patagonia Norte",
    "Patagonia Sur",
    "Regional Aduanera Austral",
    "Regional Aduanera Central",
    "Regional Aduanera Cuyo",
    "Regional Aduanera Hidrovía",
    "Regional Aduanera Noreste",
    "Regional Aduanera Noroeste",
    "Regional Aduanera Río Colorado",
    "Regional AMBA",
    "Regional Austral",
    "Regional Bahía Blanca",
    "Regional Centro",
    "Regional Centro (Córdoba, San Luis, San Juan, La Rioja)",
    "Regional Centro II",
    "Regional Comodoro Rivadavia",
    "Regional Córdoba",
    "Regional Junín",
    "Regional La Plata",
    "Regional Mar del Plata",
    "Regional Mendoza",
    "Regional Mercedes",
    "Regional Microcentro",
    "Regional NEA (Entre Ríos, Corrientes, Misiones)",
    "Regional Neuquén",
    "Regional NOA (Salta, Jujuy, Tucumán, Catamarca)",
    "Regional Norte",
    "Regional Norte (Chaco, Formosa, Santiago del Estero, Santa Fe)",
    "Regional Oeste",
    "Regional Palermo",
    "Regional Pampeana (La Pampa, Buenos Aires, Mendoza)",
    "Regional Paraná",
    "Regional Patagónica (Río Negro, Neuquén, Chubut, Santa Cruz, Tierra del Fuego, Antártida e Islas del Atlántico Sur)",
    "Regional Posadas",
    "Regional Resistencia",
    "Regional Río Cuarto",
    "Regional Rosario",
    "Regional Sur",
    "Región Centro",
    "Región Norte",
    "Región Norte",
    "Región Patagonia",
    "Región Semiárida",
    "Región Sur",
]


JURISDICTION_COLORS = {
  "Jefatura de Gabinete de Ministros": "#007bff",
  "Ministerio de Ambiente y Desarrollo Sostenible": "#ff6600",
  "Ministerio de Ciencia, Tecnología e Innovación": "#28a745",
  "Ministerio de Cultura": "#e41a1c",
  "Ministerio de Defensa": "#8e44ad",
  "Ministerio de Desarrollo Social": "#a0522d",
  "Ministerio de Desarrollo Territorial y Hábitat": "#ff69b4",
  "Ministerio de Economía": "#555555",
  "Ministerio de Educación": "#d4e157",
  "Ministerio de Justicia y Derechos Humanos": "#00ced1",
  "Ministerio de las Mujeres, Géneros y Diversidad": "#4b0082",
  "Ministerio de Obras Públicas": "#3cb371",
  "Ministerio de Relaciones Exteriores, Comercio Internacional y Culto": "#cd853f",
  "Ministerio de Salud": "#b22222",
  "Ministerio de Seguridad": "#9932cc",
  "Ministerio de Trabajo, Empleo y Seguridad Social": "#ff4d4d",
  "Ministerio de Transporte": "#4169e1",
  "Ministerio de Turismo y Deportes": "#66bb6a",
  "Ministerio del Interior": "#daa520",
  "Secretaría de Asuntos Estratégicos": "#c0392b",
  "Secretaría de Comunicación y Prensa": "#ba55d3",
  "Secretaría General": "#7b68ee",
  "Secretaría Legal y Técnica": "#9acd32",
  "Ministerio de Capital Humano": "#d4e157",
  "Ministerio de Desregulación y Transformación del Estado": "#4b0082",
  "Ministerio de Justicia": "#00ced1",
  "Ministerio de Seguridad Nacional": "#9932cc",
  "Secretaría de Comunicación y Medios": "#ba55d3",
  "Secretaría de Cultura": "#e41a1c",
  "Secretaría de Inteligencia de Estado": "#daa520"
}


class DimensionName(str, Enum):
    OBJECTIVE = "objetivos"
    TARGET = "destinatarios"
    ENVIRONMENT = "ambitos"
    DISTANCE = "distancia"


LLM_BASED_DIMENSIONS = [
    DimensionName.OBJECTIVE,
    DimensionName.TARGET,
    DimensionName.ENVIRONMENT,
]
